# Generated by Django 2.1.3 on 2018-11-21 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcDc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('ani0', models.IntegerField()),
                ('ani1', models.IntegerField()),
                ('ani2', models.IntegerField()),
                ('ani3', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pressures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(verbose_name='date_time')),
                ('pressure', models.IntegerField(verbose_name='pressure')),
                ('temperature', models.IntegerField(verbose_name='temperature')),
            ],
        ),
        migrations.CreateModel(
            name='Sensors',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('sensor_type', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('add_datetime', models.DateTimeField()),
                ('remove_datetime', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='pressures',
            name='sensor_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensors_name', to='data_view.Sensors', verbose_name='sensor_name'),
        ),
        migrations.AddField(
            model_name='acdc',
            name='sensor_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensor_acdc_name', to='data_view.Sensors'),
        ),
    ]
