# Generated by Django 2.1.3 on 2018-11-07 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
