# Generated by Django 2.1.3 on 2018-11-08 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_acdc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pressures',
            name='date_time',
            field=models.DateTimeField(verbose_name='date_time'),
        ),
        migrations.AlterField(
            model_name='pressures',
            name='pressure',
            field=models.IntegerField(verbose_name='pressure'),
        ),
        migrations.AlterField(
            model_name='pressures',
            name='sensor_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensors_name', to='project.Sensors', verbose_name='sensor_name'),
        ),
        migrations.AlterField(
            model_name='pressures',
            name='temperature',
            field=models.IntegerField(verbose_name='temperature'),
        ),
    ]
